-- SkinMinder Seed Data
-- Run this in your Supabase SQL Editor after the migration

-- ============ INGREDIENTS (50 common cosmetic ingredients) ============
INSERT INTO ingredients (name, function, benefits, skin_types_suited, is_irritant, irritant_severity, description) VALUES
('Niacinamide', 'Skin conditioning', ARRAY['oil regulation', 'pore minimizing', 'brightening', 'barrier support'], ARRAY['oily', 'combination', 'normal', 'sensitive'], false, null, 'Vitamin B3 derivative that regulates sebum production and improves skin barrier function'),
('Hyaluronic Acid', 'Humectant', ARRAY['hydration', 'plumping', 'moisture retention'], ARRAY['dry', 'oily', 'combination', 'normal', 'sensitive'], false, null, 'Powerful humectant that holds up to 1000x its weight in water'),
('Retinol', 'Anti-aging', ARRAY['cell turnover', 'wrinkle reduction', 'collagen stimulation', 'anti-aging'], ARRAY['normal', 'oily', 'combination'], true, 'mild', 'Vitamin A derivative that accelerates cell turnover and boosts collagen production'),
('Salicylic Acid', 'Exfoliant', ARRAY['acne treatment', 'pore clearing', 'exfoliation', 'oil control'], ARRAY['oily', 'combination'], true, 'mild', 'BHA that penetrates pores to dissolve dead skin cells and excess oil'),
('Vitamin C (Ascorbic Acid)', 'Antioxidant', ARRAY['brightening', 'antioxidant protection', 'collagen synthesis', 'dark spot reduction'], ARRAY['normal', 'dry', 'combination'], true, 'mild', 'Potent antioxidant that brightens skin and protects against environmental damage'),
('Glycerin', 'Humectant', ARRAY['hydration', 'moisture barrier support'], ARRAY['dry', 'oily', 'combination', 'normal', 'sensitive'], false, null, 'Simple humectant that draws moisture to the skin'),
('Ceramides', 'Skin barrier', ARRAY['barrier repair', 'moisture lock', 'protection'], ARRAY['dry', 'sensitive', 'normal'], false, null, 'Lipids naturally found in skin that maintain the moisture barrier'),
('Azelaic Acid', 'Anti-inflammatory', ARRAY['redness reduction', 'acne treatment', 'brightening', 'anti-inflammatory'], ARRAY['sensitive', 'oily', 'combination', 'normal'], false, null, 'Gentle acid with anti-inflammatory and antimicrobial properties'),
('Glycolic Acid', 'Exfoliant', ARRAY['exfoliation', 'brightening', 'texture improvement'], ARRAY['normal', 'oily', 'combination'], true, 'moderate', 'AHA that exfoliates the surface layer of skin for smoother texture'),
('Lactic Acid', 'Exfoliant', ARRAY['gentle exfoliation', 'hydration', 'brightening'], ARRAY['dry', 'sensitive', 'normal'], true, 'mild', 'Gentle AHA derived from milk that exfoliates while hydrating'),
('Squalane', 'Emollient', ARRAY['hydration', 'softening', 'antioxidant'], ARRAY['dry', 'sensitive', 'normal', 'oily'], false, null, 'Lightweight oil that mimics skin natural sebum'),
('Centella Asiatica', 'Soothing', ARRAY['calming', 'wound healing', 'anti-inflammatory'], ARRAY['sensitive', 'dry', 'normal', 'combination'], false, null, 'Plant extract known for healing and soothing irritated skin'),
('Tea Tree Oil', 'Antimicrobial', ARRAY['acne treatment', 'antimicrobial', 'anti-inflammatory'], ARRAY['oily', 'combination'], true, 'mild', 'Essential oil with natural antibacterial properties'),
('Benzoyl Peroxide', 'Acne treatment', ARRAY['acne treatment', 'antibacterial'], ARRAY['oily', 'combination'], true, 'moderate', 'Strong antibacterial agent that kills acne-causing bacteria'),
('Peptides', 'Anti-aging', ARRAY['collagen stimulation', 'firmness', 'anti-aging'], ARRAY['dry', 'normal', 'combination', 'sensitive'], false, null, 'Short chains of amino acids that signal skin to produce more collagen'),
('Zinc Oxide', 'Sun protection', ARRAY['UV protection', 'anti-inflammatory', 'soothing'], ARRAY['sensitive', 'dry', 'normal', 'oily', 'combination'], false, null, 'Physical sunscreen agent that reflects UV rays'),
('Titanium Dioxide', 'Sun protection', ARRAY['UV protection'], ARRAY['sensitive', 'dry', 'normal', 'oily', 'combination'], false, null, 'Physical sunscreen agent providing broad-spectrum protection'),
('Alpha Arbutin', 'Brightening', ARRAY['dark spot reduction', 'brightening', 'pigmentation control'], ARRAY['normal', 'dry', 'combination', 'sensitive'], false, null, 'Gentle skin brightener that inhibits melanin production'),
('Kojic Acid', 'Brightening', ARRAY['brightening', 'dark spot treatment'], ARRAY['normal', 'oily', 'combination'], true, 'mild', 'Derived from fungi, helps lighten visible sun damage and dark spots'),
('Bakuchiol', 'Anti-aging', ARRAY['anti-aging', 'firmness', 'retinol alternative'], ARRAY['sensitive', 'dry', 'normal', 'combination'], false, null, 'Plant-based retinol alternative with similar anti-aging benefits'),
('Aloe Vera', 'Soothing', ARRAY['soothing', 'hydration', 'healing'], ARRAY['sensitive', 'dry', 'normal', 'oily', 'combination'], false, null, 'Natural plant gel that soothes and hydrates irritated skin'),
('Shea Butter', 'Emollient', ARRAY['deep moisturizing', 'softening', 'barrier protection'], ARRAY['dry', 'normal'], false, null, 'Rich butter that deeply moisturizes and protects skin'),
('Jojoba Oil', 'Emollient', ARRAY['moisturizing', 'oil balancing', 'softening'], ARRAY['dry', 'normal', 'combination'], false, null, 'Oil similar to natural sebum that moisturizes without clogging pores'),
('Green Tea Extract', 'Antioxidant', ARRAY['antioxidant', 'anti-inflammatory', 'oil control'], ARRAY['oily', 'combination', 'normal', 'sensitive'], false, null, 'Rich in polyphenols that protect against environmental damage'),
('Witch Hazel', 'Astringent', ARRAY['pore tightening', 'oil control'], ARRAY['oily', 'combination'], true, 'mild', 'Natural astringent that can help control oil production'),
('Panthenol', 'Skin conditioning', ARRAY['hydration', 'healing', 'soothing'], ARRAY['dry', 'sensitive', 'normal', 'combination', 'oily'], false, null, 'Provitamin B5 that moisturizes and promotes skin healing'),
('Allantoin', 'Soothing', ARRAY['soothing', 'healing', 'moisturizing'], ARRAY['sensitive', 'dry', 'normal'], false, null, 'Gentle ingredient that soothes irritation and promotes healing'),
('Rosehip Oil', 'Emollient', ARRAY['anti-aging', 'brightening', 'scar healing'], ARRAY['dry', 'normal', 'combination'], false, null, 'Oil rich in vitamins A and C that helps with scarring and aging'),
('Mandelic Acid', 'Exfoliant', ARRAY['gentle exfoliation', 'acne treatment', 'brightening'], ARRAY['sensitive', 'oily', 'combination'], true, 'mild', 'Large-molecule AHA suitable for sensitive skin'),
('Tranexamic Acid', 'Brightening', ARRAY['dark spot reduction', 'brightening', 'redness reduction'], ARRAY['normal', 'sensitive', 'combination', 'dry'], false, null, 'Targets hyperpigmentation and reduces redness'),
('Snail Mucin', 'Skin repair', ARRAY['hydration', 'healing', 'anti-aging'], ARRAY['dry', 'normal', 'combination', 'sensitive'], false, null, 'Rich in glycoproteins that help repair and hydrate skin'),
('Colloidal Oatmeal', 'Soothing', ARRAY['soothing', 'anti-itch', 'barrier protection'], ARRAY['sensitive', 'dry'], false, null, 'FDA-approved skin protectant that soothes irritation'),
('Ferulic Acid', 'Antioxidant', ARRAY['antioxidant', 'UV protection boost', 'anti-aging'], ARRAY['normal', 'oily', 'combination'], false, null, 'Antioxidant that enhances the stability of vitamins C and E'),
('Vitamin E (Tocopherol)', 'Antioxidant', ARRAY['antioxidant', 'moisturizing', 'healing'], ARRAY['dry', 'normal', 'sensitive'], false, null, 'Fat-soluble antioxidant that protects and moisturizes skin'),
('Licorice Root Extract', 'Brightening', ARRAY['brightening', 'anti-inflammatory', 'soothing'], ARRAY['sensitive', 'normal', 'combination'], false, null, 'Natural brightener with anti-inflammatory properties'),
('Caffeine', 'Stimulant', ARRAY['de-puffing', 'antioxidant', 'circulation boost'], ARRAY['normal', 'oily', 'combination'], false, null, 'Constricts blood vessels to reduce puffiness and dark circles'),
('Sodium Hyaluronate', 'Humectant', ARRAY['deep hydration', 'plumping'], ARRAY['dry', 'oily', 'combination', 'normal', 'sensitive'], false, null, 'Smaller molecule form of hyaluronic acid that penetrates deeper'),
('Dimethicone', 'Emollient', ARRAY['smoothing', 'moisture lock', 'protection'], ARRAY['normal', 'dry', 'combination'], false, null, 'Silicone that creates a smooth protective layer on skin'),
('Urea', 'Humectant', ARRAY['hydration', 'gentle exfoliation', 'softening'], ARRAY['dry', 'normal'], true, 'mild', 'Natural moisturizing factor that hydrates and gently exfoliates'),
('Sulfur', 'Acne treatment', ARRAY['acne treatment', 'oil absorption', 'antibacterial'], ARRAY['oily', 'combination'], true, 'moderate', 'Mineral that absorbs excess oil and treats acne'),
('Adapalene', 'Retinoid', ARRAY['acne treatment', 'anti-aging', 'cell turnover'], ARRAY['oily', 'combination', 'normal'], true, 'moderate', 'Third-generation retinoid effective for acne and aging'),
('Propolis', 'Antibacterial', ARRAY['healing', 'antibacterial', 'anti-inflammatory'], ARRAY['oily', 'combination', 'sensitive'], false, null, 'Bee-derived ingredient with natural antibacterial properties'),
('Mugwort', 'Soothing', ARRAY['calming', 'anti-inflammatory', 'antioxidant'], ARRAY['sensitive', 'normal', 'combination'], false, null, 'Traditional herb that calms irritated and sensitive skin'),
('Rice Extract', 'Brightening', ARRAY['brightening', 'moisturizing', 'antioxidant'], ARRAY['normal', 'dry', 'combination', 'sensitive'], false, null, 'Traditional Asian ingredient that brightens and nourishes skin'),
('Turmeric', 'Anti-inflammatory', ARRAY['anti-inflammatory', 'brightening', 'antioxidant'], ARRAY['normal', 'oily', 'combination'], true, 'mild', 'Spice with potent anti-inflammatory and brightening properties'),
('Charcoal', 'Purifying', ARRAY['pore cleansing', 'oil absorption', 'detoxifying'], ARRAY['oily', 'combination'], false, null, 'Draws out impurities and absorbs excess oil from pores'),
('Fragrance', 'Fragrance', ARRAY[], ARRAY[], true, 'moderate', 'Synthetic or natural scent added to products. Common irritant and allergen'),
('Alcohol Denat', 'Solvent', ARRAY['fast absorption'], ARRAY[], true, 'moderate', 'Denatured alcohol used as solvent. Can be drying and irritating'),
('Essential Oils (Mixed)', 'Fragrance', ARRAY['aromatherapy'], ARRAY[], true, 'mild', 'Concentrated plant extracts that can cause irritation in sensitive skin'),
('Parabens', 'Preservative', ARRAY['product preservation'], ARRAY[], true, 'mild', 'Synthetic preservatives. Controversial but FDA considers safe at low levels');

-- ============ PRODUCTS (20 sample products) ============
INSERT INTO products (name, brand, category, ingredients, skin_targets, price) VALUES
('Vitamin C Brightening Serum', 'GlowLab', 'serum', ARRAY['Vitamin C (Ascorbic Acid)', 'Ferulic Acid', 'Vitamin E (Tocopherol)', 'Hyaluronic Acid'], ARRAY['brightening', 'anti-aging', 'dark spots'], 34.99),
('Hydrating Gel Moisturizer', 'AquaSkin', 'moisturizer', ARRAY['Hyaluronic Acid', 'Glycerin', 'Aloe Vera', 'Panthenol'], ARRAY['hydration', 'sensitive skin'], 28.00),
('Niacinamide Oil Control Serum', 'PorePerfect', 'serum', ARRAY['Niacinamide', 'Zinc Oxide', 'Green Tea Extract'], ARRAY['oil control', 'pore minimizing'], 22.50),
('Gentle Foaming Cleanser', 'SkinFirst', 'cleanser', ARRAY['Glycerin', 'Ceramides', 'Panthenol', 'Allantoin'], ARRAY['sensitive skin', 'hydration'], 18.00),
('Retinol Night Cream', 'AgelessSkin', 'moisturizer', ARRAY['Retinol', 'Peptides', 'Squalane', 'Ceramides'], ARRAY['anti-aging', 'wrinkles', 'fine lines'], 48.00),
('BHA Exfoliating Toner', 'ClearZone', 'toner', ARRAY['Salicylic Acid', 'Niacinamide', 'Green Tea Extract', 'Centella Asiatica'], ARRAY['acne', 'pore clearing', 'oil control'], 24.00),
('Centella Soothing Cream', 'CalmSkin', 'moisturizer', ARRAY['Centella Asiatica', 'Ceramides', 'Panthenol', 'Allantoin'], ARRAY['sensitive skin', 'redness', 'irritation'], 26.00),
('Mineral Sunscreen SPF 50', 'SunShield', 'sunscreen', ARRAY['Zinc Oxide', 'Titanium Dioxide', 'Squalane', 'Vitamin E (Tocopherol)'], ARRAY['sun protection', 'sensitive skin'], 32.00),
('AHA Brightening Mask', 'GlowRitual', 'mask', ARRAY['Glycolic Acid', 'Lactic Acid', 'Hyaluronic Acid', 'Aloe Vera'], ARRAY['brightening', 'exfoliation', 'texture'], 30.00),
('Dark Spot Corrector', 'EvenTone', 'serum', ARRAY['Alpha Arbutin', 'Tranexamic Acid', 'Niacinamide', 'Licorice Root Extract'], ARRAY['dark spots', 'hyperpigmentation', 'brightening'], 36.00),
('Snail Mucin Essence', 'KBeautyPro', 'serum', ARRAY['Snail Mucin', 'Hyaluronic Acid', 'Panthenol', 'Centella Asiatica'], ARRAY['hydration', 'healing', 'anti-aging'], 25.00),
('Tea Tree Spot Treatment', 'ClearZone', 'serum', ARRAY['Tea Tree Oil', 'Salicylic Acid', 'Centella Asiatica'], ARRAY['acne', 'spot treatment'], 15.00),
('Bakuchiol Anti-Aging Serum', 'NaturAge', 'serum', ARRAY['Bakuchiol', 'Squalane', 'Rosehip Oil', 'Vitamin E (Tocopherol)'], ARRAY['anti-aging', 'sensitive skin', 'wrinkles'], 38.00),
('Caffeine Eye Cream', 'BrightEyes', 'eye cream', ARRAY['Caffeine', 'Peptides', 'Hyaluronic Acid', 'Vitamin C (Ascorbic Acid)'], ARRAY['dark circles', 'puffiness', 'anti-aging'], 28.00),
('Oat Calming Cleanser', 'SoftSkin', 'cleanser', ARRAY['Colloidal Oatmeal', 'Glycerin', 'Ceramides', 'Aloe Vera'], ARRAY['sensitive skin', 'soothing', 'gentle cleansing'], 16.00),
('Propolis Glow Serum', 'HoneyDew', 'serum', ARRAY['Propolis', 'Niacinamide', 'Hyaluronic Acid'], ARRAY['healing', 'glow', 'hydration'], 29.00),
('Rice Water Toner', 'KBeautyPro', 'toner', ARRAY['Rice Extract', 'Glycerin', 'Panthenol', 'Centella Asiatica'], ARRAY['brightening', 'hydration', 'gentle'], 20.00),
('Azelaic Acid Gel', 'DermClear', 'serum', ARRAY['Azelaic Acid', 'Niacinamide', 'Aloe Vera'], ARRAY['redness', 'acne', 'brightening'], 22.00),
('Intensive Repair Body Lotion', 'BodyBliss', 'body lotion', ARRAY['Shea Butter', 'Ceramides', 'Urea', 'Glycerin'], ARRAY['dry skin', 'body care', 'deep moisturizing'], 20.00),
('Mugwort Calming Mask', 'HerbalGlow', 'mask', ARRAY['Mugwort', 'Centella Asiatica', 'Aloe Vera', 'Green Tea Extract'], ARRAY['calming', 'sensitive skin', 'anti-inflammatory'], 24.00);
