-- Routine versioning for longitudinal tracking
CREATE TABLE IF NOT EXISTS routine_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  routine JSONB NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  concerns TEXT[] DEFAULT '{}',
  skin_type TEXT,
  changelog TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, version)
);

CREATE INDEX IF NOT EXISTS idx_routine_versions_user_id ON routine_versions(user_id);
CREATE INDEX IF NOT EXISTS idx_routine_versions_created_at ON routine_versions(created_at);

-- Store current active routine
CREATE TABLE IF NOT EXISTS user_active_routine (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  current_version INTEGER NOT NULL DEFAULT 1,
  routine JSONB NOT NULL,
  concerns TEXT[] DEFAULT '{}',
  skin_type TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);