-- Retention engine: Scheduled reminders for user engagement
CREATE TABLE IF NOT EXISTS reminder_schedule (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL CHECK (type IN (
    'first_scan', 'weekly_scan', 'scan_streak', 'routine_check', 'progress_milestone', 'product_expire'
  )),
  scheduled_at TIMESTAMPTZ NOT NULL,
  sent BOOLEAN DEFAULT FALSE,
  completed BOOLEAN DEFAULT FALSE,
  message TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reminder_schedule_user_id ON reminder_schedule(user_id);
CREATE INDEX IF NOT EXISTS idx_reminder_schedule_scheduled_at ON reminder_schedule(scheduled_at);
CREATE INDEX IF NOT EXISTS idx_reminder_schedule_pending ON reminder_schedule(sent, scheduled_at) WHERE sent = FALSE;

-- Track scan streaks for gamification
CREATE TABLE IF NOT EXISTS scan_streaks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  current_streak INTEGER DEFAULT 0,
  longest_streak INTEGER DEFAULT 0,
  last_scan_date DATE,
  streak_start_date DATE,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_scan_streaks_user_id ON scan_streaks(user_id);

-- User engagement analytics
CREATE TABLE IF NOT EXISTS engagement_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  sessions INTEGER DEFAULT 0,
  scans_completed INTEGER DEFAULT 0,
  time_spent_seconds INTEGER DEFAULT 0,
  features_used TEXT[] DEFAULT '{}',
  UNIQUE (user_id, date)
);

CREATE INDEX IF NOT EXISTS idx_engagement_metrics_user_date ON engagement_metrics(user_id, date);